#!/bin/bash

#Set the name of the algorithm's Java class
ALGO=Mocca

#Name of the dataset
DATASET=breast

#JVM arguments
ARGS=""

#Main class
MAIN="weka.subspaceClusterer.Run"

#Directories
CPATH=$RCAC_SCRATCH/oss
JOBS=$RCAC_SCRATCH/jobs
RESULTDIR=$RCAC_SCRATCH/results
DATAFILES=$RCAC_SCRATCH/data/*.arff

#MOCCA algorithm parameters
alpha=0.05
exp_label=0
maxiter=2000000

#Create the scripts that will run the jobs. 
#Each jobfile will is one run in the experiement. 
#Each loop below varies one parameter of the experiment.

for pca in y n
do 
for minDiscrimSetSize in 2 3 4
do
for width in 0.0005 0.001 0.01 0.08
do
for epsilon in 0.005 
do
for qualityThreshold in 0
do
for beta in 0.25 0.35
do
for subspaceSimilarityThreshold in -1
do
for clusterSimilarityThreshold in 0 0.15 
do
for file in $DATAFILES
do

    JOBFILE=$JOBS/$exp_label.sh

    #Load java into environment
    echo "module load java" >> $JOBFILE

    #Set up the executable command
    CMD="java $ARGS -cp \"$CPATH/*\" $MAIN -sc $ALGO -label $exp_label -a $alpha -maxiter $maxiter -pca $pca -mindiscrim $minDiscrimSetSize -w $width -e $epsilon -minqual $qualityThreshold -b $beta -s $subspaceSimilarityThreshold -i $clusterSimilarityThreshold -t $file -path $RESULTDIR -M F1Measure:Accuracy:Entropy:Coverage -c last"

    #Run clustering algo
    echo $CMD >> $JOBFILE
    
    #Make the job executable
    chmod u+x $JOBFILE 

    #Update the label
    exp_label=$((exp_label + 1))

done
done
done
done
done
done
done 
done
done

echo "Created $((exp_label)) files.  PBS_ARRAYID 0 - $((exp_label-1))."

