#!/bin/bash
#First argument is the next job to run
#Second argument is the last jobb to run
#Third argument is limit on the number of concurrent jobs
#Fourth arguemnt is queue name
#Fifth argument is the name of the script to run. Use absolute path.

NEXTJOB=$1
LAST=$2
LIMIT=$3
Q=$4
JOB=$5
SCHLAFEN=10

while [[ $NEXTJOB -le $LAST ]]
do
  TOTAL=$(qstat -u hoffer $Q | grep -c hoffer)
  SLOT=$((LIMIT-TOTAL))
  while [[ $SLOT -gt 0 && $NEXTJOB -le $LAST ]]
  do
    echo "Submitting $NEXTJOB"
    $JOB $NEXTJOB $Q
    NEXTJOB=$((NEXTJOB+1))
    SLOT=$((SLOT-1))
    sleep 0.1
  done   
  echo "sleeping..."
  sleep $SCHLAFEN
done
  echo "All jobs submitted to $Q"
