#!/bin/bash
#First argument is the number jobs
#Second argument is the slot limt

NEXTJOB=$1
LAST=$2
SLOTLIMIT=$3

JOB="/home/hoffer/runone"
TOTAL=0
SCHLAFEN=6
Q=standby

#I am missing jobs because they take a while to show up.
#first, submit slotlimit -1, then wait 20 seconds or so.

while [ $NEXTJOB -le $LAST ] 
do
  #DEBUG
  #echo "Top of loop start=$START, stop=$STOP, num running=$RUNNING"

  if [ $TOTAL -lt "$SLOTLIMIT" ]
  then
    echo "Submitting $NEXTJOB"
    $JOB $NEXTJOB
    NEXTJOB=$((NEXTJOB+1))
  else 
    echo "sleeping..."
    sleep $SCHLAFEN
  fi
  
  TOTAL=$(qstat -u hoffer $Q | grep -c hoffer)
  
  #DEBUG
  echo "Num in process $TOTAL, Next job num $NEXTJOB "

done
