#!/bin/bash
#First argument must be filename
#Second argument is queue name. Optional.

if [ -z $2 ] 
then 
  Q=standby
else 
  Q=$2
fi

qsub $RCAC_SCRATCH/jobs/$1.sh -A TG-AST080043 -e $RCAC_SCRATCH/out -j eo  -l nodes=1:ppn=1  -l walltime=01:00:00 -q $Q
