function results=sepc(data, width, alpha, beta, epsilon, ...
    subspace_overlap_threshold, ...
    object_overlap_threshold)

num_dims=columns(data);
num_trials=ktrials(epsilon, alpha, beta, num_dims);
discrim_set_size=max(2, s_est(num_dims, beta));
fprintf('Number of trials=%d\n', num_trials);
results=cluster(data, width, alpha, beta, ...
    subspace_overlap_threshold, ...
    object_overlap_threshold, ...
    num_trials, ...
    discrim_set_size);

end
